# Site settings
title: 一切都是最好的安排
email: boyishwei@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
   Ryan, an software engineer, a fullstack web developer, fascinating in Ruby, JS & webbased techs...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: boyishwei 
github_username:  boyishwei 

# Build settings
markdown: kramdown

exclude: [vendor]
